version: '3'
services:
  
  # Node.js Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - .:/var/www # Mount your project folder
      - /var/www/node_modules # Ensure node_modules are mounted properly
    ports:
      - "3000:3000"
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
