name: Deploy Site via Git

on:
  push:
    branches:
      - main  # Run this workflow whenever code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: SSH into the VPS and pull the latest code
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_IP }}   # Your VPS IP address stored as a secret
          username: ${{ secrets.VPS_USER }}  # Your VPS user stored as a secret
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your SSH private key stored as a secret
          script: |
            cd Valkyrie/Valk.Website/AlphaBloxWeb        # Navigate to your project directory
            git pull origin main        # Pull the latest code from GitHub
            npm install                 # Install any new dependencies
            docker-compose down         # Stop running containers if using Docker
            docker-compose up -d        # Restart the app in detached mode
